"""Added inventory_id column for schedule

Revision ID: 4fc231816655
Revises: d945da89599c
Create Date: 2024-01-07 11:27:52.029590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc231816655'
down_revision = 'd945da89599c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('inventory_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'inventory_id')
    # ### end Alembic commands ###
