"""update Forgot Password table

Revision ID: 59bc2cc318da
Revises: 98cca59f6e1a
Create Date: 2023-11-28 14:37:11.072682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59bc2cc318da'
down_revision = '98cca59f6e1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forgot_password', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'forgot_password', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forgot_password', type_='unique')
    op.drop_column('forgot_password', 'created_at')
    # ### end Alembic commands ###
