"""Update schedules table to be text

Revision ID: 6acef6edafc6
Revises: 3e4ea1d3c842
Create Date: 2023-12-14 14:48:57.659638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import BYTEA


# revision identifiers, used by Alembic.
revision = '6acef6edafc6'
down_revision = '3e4ea1d3c842'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'image',
               existing_type=BYTEA,
               type_=sa.Text)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'image',
               type_=sa.Text,
               nullable=True)
    # ### end Alembic commands ###
