"""update Forgot Password table

Revision ID: b949ec822291
Revises: 59bc2cc318da
Create Date: 2023-11-28 14:42:26.180047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b949ec822291'
down_revision = '59bc2cc318da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forgot_password', sa.Column('identifier', sa.Text(), nullable=True))
    op.drop_constraint('forgot_password_status_key', 'forgot_password', type_='unique')
    op.create_unique_constraint(None, 'forgot_password', ['identifier'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forgot_password', type_='unique')
    op.create_unique_constraint('forgot_password_status_key', 'forgot_password', ['status'])
    op.drop_column('forgot_password', 'identifier')
    # ### end Alembic commands ###
