"""Update stock column to be numeric in inventory table

Revision ID: d945da89599c
Revises: 6acef6edafc6
Create Date: 2024-01-07 04:38:02.913418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd945da89599c'
down_revision = '6acef6edafc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory', 'stock',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory', 'stock',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
