"""updated ID length to 36

Revision ID: dc310e660c23
Revises: ab75350b73a1
Create Date: 2023-05-14 03:57:50.420705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc310e660c23'
down_revision = 'ab75350b73a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
