@startuml HealthMate - General use-case diagram
left to right direction
actor "User" as user
rectangle "HealthMate - General use-case diagram" as app {
  usecase "Login" as Auth1
  usecase "Register" as Auth2
  usecase "Medication Reminder" as UC1
  usecase "Manage Medicine Inventory" as UC2
  usecase "Symptom Checker" as UC3
}
user --> Auth1
user --> Auth2
user --> UC1
user --> UC2
user --> UC3
@enduml