@startuml HealthMate - General use-case diagram
left to right direction
actor "User" as user
actor "Doctor" as doctor
rectangle "HealthMate - General use-case diagram" as app {
  usecase "Login" as Auth1
  usecase "Register" as Auth2
  usecase "Set Medication Reminder" as UC1
  usecase "Receive Medication Reminder" as UC2
  usecase "Track Medication History" as UC3
  usecase "View Medication Analytics" as UC4
  usecase "Share Medication Analytics" as UC5
}
user --> Auth1
user --> Auth2
user --> UC1
user --> UC2
user --> UC3
user --> UC4
user --> UC5
UC5 --> doctor
@enduml