name: Trigger auto deployment for healthmate-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/healthmate-api-AutoDeployTrigger-caa7b2fc-c28e-4123-abd6-58222f930642.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.HEALTHMATEAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HEALTHMATEAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HEALTHMATEAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: jtmarilao.azurecr.io
          registryUsername: ${{ secrets.HEALTHMATEAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HEALTHMATEAPI_REGISTRY_PASSWORD }}
          containerAppName: healthmate-api
          resourceGroup: capstone
          imageToBuild: jtmarilao.azurecr.io/healthmate-api:${{ github.sha }}
          dockerfilePath: Dockerfile


